version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command:
      - /start.sh
    ports:
      - 8777:8777
      - 8443:8443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  backend:
    container_name: echo
    build:
      context: .
      dockerfile: ./docker/echo/Dockerfile
    ports:
      - 3030:3030
    working_dir: /app
    tty: true

  frontend:
    ## image: svelte
    container_name: svelte
    build:
      context: .
      dockerfile: ./docker/svelte/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/svelte.config.js:/app/svelte.config.js
