version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command:
      - /start.sh
    ports:
      - 8000:8000
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  deno:
    container_name: deno
    build:
      context: .
      dockerfile: ./docker/Deno/Dockerfile
    ports:
      - 1993:1993
    volumes:
      - ./src:/app
    tty: true