version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command:
      - /start.sh
    ports:
      - 8777:8777
      - 8443:8443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  echo:
    container_name: echo
    build:
      context: .
      dockerfile: ./docker/echo/Dockerfile
    ports:
      - 1993:1993
    working_dir: /app
    tty: true